version: '3.8'

services:
  mysql:
    platform: linux/x86_64
    container_name: mysql
    image: mysql:5.7 #mysql:8.0だとmysql2がいるけどdataSourceのtypeにはそれがないので仕方なく5.7使う
    restart: always
    env_file:
      - .env
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  data:

# メモ：MYSQL_ROOT_PASSWORDとかを書き換えた後ボリュームが残っていると資格情報も残ってしまいエラーが出るので、その時はdocker volume rm <volume_name> を実行する